```{r}
library(dplyr)
```
Tarea 3
```{r}
#setwd("E:/Miguel/Universidad/Maestria/Segundo Trimestre/FUNDAMENTOS DE PROGRAMACION Y SCRIPTING/Tareas/Homework-3/")
dataset_results <- read.csv(file = "primary_results.csv", header = TRUE, sep = ",", quote = "\"", dec = ".")

dataset_results

```
1
```{r}
#subset(dataset_results, state == "Florida")

dataset_results %>%
  filter(state == "Florida")
```
2.1
```{r}
dataset_results %>%
  filter(candidate == "Hillary Clinton" | candidate == "Donald Trump")
```
2.2
```{r}
dataset_results %>%
  filter(party == "Democrat" & county == "Shelby")
```
2.3
```{r}
dataset_results %>%
  filter(state == "Alabama" & votes > 15000)
```
3.1
```{r}
dataset_results %>%
  filter(state == "Texas" & county == "Denton")%>%
  select(party, candidate, votes)%>%
  arrange(desc(votes))
```
4.1
```{r}
dataset_results %>%
  filter(party == "Republican" & candidate == "Ted Cruz" & state == "Alaska")%>%
  mutate(vote_count = votes/fraction_votes)%>%
  arrange(desc(vote_count))
```

