Tarea 4
```{r}
library(dplyr)
library(ggplot2)
diamonds <- read.csv(file = "diamonds.csv", header = TRUE, sep = ",", quote = "\"", dec = ".")
diamonds
```
1
```{r}
ggplot(diamonds, aes(x=carat, y=price)) +
  geom_point() 

ggplot(diamonds, aes(x=carat, y=price, color=clarity)) +
  geom_point() 
```
2
```{r}
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins = 40)
  
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins = 40) +
  scale_x_log10()
```
3
```{r}
ggplot(diamonds, aes(x=cut, y=price))+
  geom_boxplot()+
  scale_y_log10()

ggplot(diamonds, aes(x=cut, y=price, fill=cut))+
  geom_boxplot()+
  scale_y_log10()
```
4.1
```{r}
filtered_price <- diamonds%>%
  filter(price > 1000 & cut%in%c("Good","Ideal","Premium"))
filtered_price
```
4.2, 4.3, 4.4
```{r}
ggplot(filtered_price, aes(x=cut, y=depth)) + 
  geom_col()

ggplot(filtered_price, aes(x=cut, y=depth)) + 
  geom_col() +
  facet_wrap(~ clarity)

ggplot(filtered_price, aes(x=cut, y=depth, fill=clarity)) + 
  geom_col() +
  facet_wrap(~ clarity)
```
Grouping and Summarizing
1
```{r}
median_dimension_diamond <- diamonds %>%
  group_by(cut)%>%
  summarize(mediaX = median(x), mediaY = median(y), mediaZ = median(z))
median_dimension_diamond
```
2
```{r}
cut_premium <- diamonds %>%
  filter(cut == "Premium") %>%
  group_by(clarity) %>%
  summarize(minPrice = min(price), maxPrice = max(price))
cut_premium
```
3
```{r}
ggplot(cut_premium, aes(x=clarity, y=maxPrice, fill=clarity)) + 
  geom_col()
```











